---
- name: Kopiera nginx-konfig för HTTPS
  ansible.builtin.copy:
    src: https.conf
    dest: /etc/nginx/conf.d/https.conf
    owner: root
    group: root
    mode: "0644"
  notify: Ladda om nginx
  become: yes
