---
- name: Se till att nginx är installerat och startat
  ansible.builtin.package:
    name: nginx
    state: present
  notify: Reload nginx

- name: Aktivera och starta nginx-tjänsten
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Kopiera vhost-konfigurationen
  ansible.builtin.copy:
    src: files/example.internal.conf
    dest: /etc/nginx/conf.d/example.internal.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Skapa docroot
  ansible.builtin.file:
    path: /var/www/example.internal/html
    state: directory
    mode: "0755"
    recurse: true

- name: Ensure /etc/pki/nginx exists
  ansible.builtin.file:
    path: /etc/pki/nginx
    state: directory
    mode: "0755"
    owner: root

- name: Ensure /etc/pki/nginx/private exists
  ansible.builtin.file:
    path: /etc/pki/nginx/private
    state: directory
    mode: "0700"
    owner: root

- name: Ensure crypto dependency is present
  ansible.builtin.package:
    name: python3-cryptography
    state: present

- name: Create private key
  community.crypto.openssl_privatekey:
    path: /etc/pki/nginx/private/server.key
    mode: "0600"

- name: Create self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/pki/nginx/server.crt
    privatekey_path: /etc/pki/nginx/private/server.key
    provider: selfsigned

- name: Kopiera nginx-konfig för HTTPS
  ansible.builtin.copy:
    src: https.conf
    dest: /etc/nginx/conf.d/https.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
