---
- name: Install and configure Node Exporter
  hosts: all
  become: true

  vars:
    node_exporter_version: "1.8.1"

  tasks:
    - name: Create node_exporter user
      ansible.builtin.user:
        name: node_exporter
        shell: /sbin/nologin
        system: yes
        create_home: no

    - name: Create textfile_collector directory
      ansible.builtin.file:
        path: /var/lib/node_exporter/textfile_collector
        state: directory
        owner: node_exporter
        group: node_exporter
        mode: '0755'
        recurse: yes

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz

    - name: Extract Node Exporter binary
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts:
          - --strip-components=1

    - name: Create sysconfig file
      ansible.builtin.copy:
        dest: /etc/sysconfig/node_exporter
        content: 'OPTIONS="--collector.textfile.directory=/var/lib/node_exporter/textfile_collector"'
        mode: '0644'

    - name: Create systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: "[Unit]\nDescription=Node Exporter\nAfter=network.target\n\n[Service]\nUser=node_exporter\nEnvironmentFile=/etc/sysconfig/node_exporter\nExecStart=/usr/local/bin/node_exporter $OPTIONS\nRestart=always\n\n[Install]\nWantedBy=multi-user.target\n"
        mode: '0644'

    - name: Enable and start Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        enabled: true
        state: started
        daemon_reload: true

    - name: Allow Node Exporter port in firewalld
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        state: enabled
        immediate: true

