---

- hosts: db
  become: true

  tasks:

    - name: Ensure MariaDB-server is installed.
      ansible.builtin.package: 
        name: mariadb-server
        state: present

    - name: Ensure mariadb service is enabled and started
      ansible.builtin.service: # använder Ansible-modulen "service" för att hantera tjänster
      
        name: mariadb
        state: started # ser till att tjänsten är igång just nu
        enabled: true
        # ser till att tjänsten startar automatiskt vid systemstart (boot)