---
- name: Konfigurera MariaDB
  hosts: db
  become: true

  vars_files:
    - vars/password.yml  # Här hämtar vi db_pass från en separat fil

  vars:
    db_name: "webappdb"
    db_user: "webappuser"
    password: "{{ db_pass }}"
    mysql_socket: "/var/lib/mysql/mysql.sock"

  tasks:
    - name: Ensure MariaDB server and PyMySQL are installed
      ansible.builtin.package:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: present

    # 2) Starta/aktivera tjänsten
    - name: Ensure mariadb service is enabled and started
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    # 3) Skapa databasen
    - name: Create database {{ db_name }}
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: "{{ mysql_socket }}"

    # 4) Skapa användaren och ge ALL på db_name.* från alla hosts (%)
    - name: Create DB user {{ db_user }} with privileges on {{ db_name }}.*
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        host: "%"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_unix_socket: "{{ mysql_socket }}"
        # Tillåt socket-root (ingen ~/.my.cnf krävs)
        check_implicit_admin: true
